umee-network/peggo

- orchestrator/cosmos/broadcast.go
- orchestrator/eth_event_watcher.go
- test/cosmos/multinode.sh
**Context**
Peggo wasn't realying the ERC20DeployedEvent messages (fired by the Peggy contract when executing deployERC20) to umee. As a consequence, Umee wasn't getting notified about the correlation of the ERC20 addresses and native coins, so when trying to send uumee from Umee to Eth, it would default to a nil address and fail to relay the coins.
**Fix**
Copied what peggo was doing for other events so now it also relays ERC20DeployedEvents.
**Notes**
Do not populate `cosmos_coin_denom` or `cosmos_coin_erc20_contract` in the genesis.
> feat: Added ERC20Deployed events

- go.mod
- go.sum
- orchestrator/cosmos/query.go
- orchestrator/main_loops.go
- orchestrator/options.go
- orchestrator/orchestrator.go
Instead of using a hard-coded user-provided ERC20 denom to contract mapping, we fetch the mapping from the chain on each request.
> refactor: query for ERC20 mapping

- cmd/peggo/flags.go
- cmd/peggo/orchestrator.go
- orchestrator/cosmos/broadcast.go
- orchestrator/eth_event_watcher.go
- orchestrator/orchestrator.go
Allow operators to supply the average cosmos block time.
ref: #42
> feat: configurable cosmos block times

- .github/workflows/lint.yml
- orchestrator/main_loops.go
Closes #45
Note: this fix can be easily applied by pulling the new version, doing `make install` and restarting the peggo service.
> fix: Request batch now creates batches for every token

- README.md
- cmd/peggo/flags.go
- cmd/peggo/tx.go
- cmd/peggo/util.go
This command was moved to the Peggy module as `set-orchestrator-address`
> chore: Remove CLI command to register Ethereum key

- CHANGELOG.md
- cmd/peggo/client/cosmos.go
- orchestrator/cosmos/broadcast.go
Now we split claims into chunks of 10 to send them in several txs instead of trying to send all of them in a single tx causing issues to syncing validators.
Also increased the timeout to 60s to match that of Althea/official Gravity Bridge https://github.com/Gravity-Bridge/Gravity-Bridge/blob/main/orchestrator/cosmos_gravity/src/send.rs#L31
I did some code reorg that's why the diff looks all weird 😓 
Closes #99
> fix: Chunk claims messages

- CHANGELOG.md
- cmd/peggo/flags.go
- cmd/peggo/orchestrator.go
- orchestrator/eth_event_watcher_test.go
- orchestrator/ethereum/committer/eth_committer.go
- orchestrator/ethereum/peggy/peggy_contract_test.go
- orchestrator/ethereum/peggy/pending_transactions_test.go
- orchestrator/ethereum/peggy/submit_batch_test.go
- orchestrator/ethereum/peggy/valset_update_test.go
- orchestrator/oracle_resync_test.go
- orchestrator/relayer/batch_relaying_test.go
Adds a flag so the gas limit is estimatedGasCost*gasLimitAdj. By default we use 1.2 as the multiplier.
Thanks @Hsiang-xxs for the suggestions 🙏 
Closes #98
> feat: Add gas limit adjustment flag

- cmd/peggo/flags.go
- cmd/peggo/orchestrator.go
- orchestrator/cosmos/broadcast.go
- orchestrator/eth_event_watcher_test.go
- orchestrator/ethereum/gravity/peggy_contract.go
- orchestrator/ethereum/gravity/peggy_contract_test.go
- orchestrator/ethereum/gravity/submit_batch.go
- orchestrator/ethereum/gravity/valset_update.go
- orchestrator/main_loops.go
- orchestrator/main_loops_test.go
- orchestrator/oracle_resync.go
- orchestrator/orchestrator.go
- orchestrator/relayer/batch_relaying.go
- orchestrator/relayer/valset_relaying.go
Fixes and refactors:
- fix hardcoded loop durations (they were changed while testing)
- fix panic on GetLastCheckedBlock (it was a matter of checking valsets last)
- added waiting loop until bridge gets deployed, if bridge-start-height is set only.
- fix power check using ints instead of percentages (ints are more accurate)
- fix retry of batches/valsets with missing confirmations. We skip those, as retrying right after doesn't help. We might need to implement a different solution if we want a more aggressive/competitive behavior.
- fix some names
- removed dead code
> fix: Cleanup and updates from Gravity Bridge

- cmd/peggo/bridge.go
- cmd/peggo/keys.go
- orchestrator/oracle_resync_test.go
- test/e2e/chain.go
- test/e2e/docker/ganache.Dockerfile
- test/e2e/e2e_setup_test.go
- test/e2e/e2e_test.go
- test/e2e/e2e_util_test.go
- test/e2e/orchestrator.go
- test/e2e/validator.go
This PR enables the use of the flag `PEGGO_E2E_USE_GANACHE=true` to run tests against a Ganache instance instead of Geth. This allows (and encourages) devs to run the E2E locally and more often. **It shouldn't be used in the CI.**
It's basically scratching my own itch of wanting to run E2E tests as fast as possible 😄
> test: Enable running tests with Ganache + test refactor + use gentx for Gravity keys

- CHANGELOG.md
- cmd/peggo/flags.go
- cmd/peggo/orchestrator.go
- orchestrator/cosmos/broadcast.go
- orchestrator/cosmos/broadcast_test.go
- orchestrator/eth_event_watcher_test.go
- orchestrator/oracle_resync_test.go
After giving this more thought, I think we need to make this configurable. Given that network conditions are always changing, we should provide a way for orchestrators to modify this in order to stay as close as possible to the nonce in the Ethereum contract.
The main example I can think of is that orchestrators should be able to send more msgs per tx during low traffic times in case they were left a bit behind; or in case a new validator wants to join.
Remember that if ~33% of orchestrators are behind, txs going from Eth to Umee will get delayed.
So, I would say that we should use a sane default but remove the hard limit and allow orchestrators to set their own value.
Added flag: `--cosmos-msgs-per-tx` with a default value of 10.
Closes: #109
> feat: Add flag to set the max amount of messages per cosmos transaction

- CHANGELOG.md
- orchestrator/coingecko/coingecko.go
- orchestrator/coingecko/coingecko_test.go
- orchestrator/coingecko/constants.go
- orchestrator/relayer/batch_relaying.go
New ERC20 tokens deployed by our Gravity contract won't be listed for an unknown time in any price tracker. For example, Gravity Bridge's NYM ERC20 isn't listed either on Coingecko nor Uniswap.
We keep a list of the ERC20 tokens that we've deployed and their matching underlying asset. We'll have to keep this list updated every time we deploy a new ERC20.
```
var bridgeTokensCoinIDs = map[string]string{
"0x0000000000000000000000000000000000000001": "atom",
"0x0000000000000000000000000000000000000002": "osmo",
"0x0000000000000000000000000000000000000003": "juno",
}
```
> feat: Add token addresses fallback

- orchestrator/coingecko/constants.go
This PR adds recently deployed ERC20 addresses to Coingecko ID pairs.
> chore: Add new ERC20s

- cmd/peggo/bridge.go
- cmd/peggo/flags.go
- cmd/peggo/orchestrator.go
Adds a log warning whenever unencrypted non-local urls are used in flags. Since it uses `url.Parse`, it should also give an error if unable to parse the url. 
Closes : #178
> fix: warn user when using unencrypted non-local urls

- CHANGELOG.md
- cmd/peggo/bridge.go
- cmd/peggo/keys.go
- cmd/peggo/orchestrator.go
Add checks where there is a user-input Eth address. We are not checking any value coming from the Cosmos gRPC, it is not necessary (and would be too late to catch a malformed address)
Closes #177
> fix: Add Ethereum addresses check

- CHANGELOG.md
- cmd/peggo/flags.go
- test/e2e/e2e_setup_test.go
Removed in favor of the env var PEGGO_COSMOS_PK
> fix: Remove cosmos-pk flag

- .golangci.yml
- Update deprecated lint options
- Running `make lint` doesn't log warnings ;D
> chore: fix lint warning

- orchestrator/oracle_resync.go
- Just separate the function to get the current block, making it possible to start the chain before the confirmation period (like devnet: ganache)
- Helps to reduce the code to review at #311
> feat: add getCurrentBlock func to return latest block confirmed

- CHANGELOG.md
- test/manual-test-peggo.md
- Updated all the old PR that we forgot to include in changelogs :/ 
- Also maybe we should delete the release and tag [v0.4.1](https://github.com/umee-network/peggo/releases/tag/v0.4.1) due to it is a breaking change updating to cosmos-sdk v046, so we should release peggo v0.5 or v1
> fix: v1 changelogs

- CHANGELOG.md
- orchestrator/main_loops.go
- orchestrator/main_loops_test.go
Matching what GB is doing in their own orchestrator.
Closes #361
> chore: modify eth block delay

- .mergify.yml
We need to rename the label [S:backport/v1.0.x](https://github.com/umee-network/peggo/labels/S%3Abackport%2Fv1.0.x) to `S:backport/v1.x.x` after this is merged
> chore: fix backport label for v1.x.x

- .github/workflows/build.yml
- .github/workflows/debug.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- .goreleaser.yml
- CHANGELOG.md
- Dockerfile
- Makefile
- cmd/peggo/orchestrator.go
- contrib/images/Dockerfile
- go.mod
- go.sum
- orchestrator/oracle/currency.go
- orchestrator/oracle/oracle.go
+ remove FTX from supported price providers
+ removed Binance from default providers
+ use PriceFeeder v2 (may solve panic issues)
> feat: update price-feeder dep to v2.0.2 and remove FTX

- contrib/images/Dockerfile
Otherwise you'd get:
```
3:15AM DBG connecting to websocket module=oracle provider=okx
3:15AM DBG connecting to websocket module=oracle provider=coinbase
3:15AM DBG connecting to websocket module=oracle provider=huobi
3:15AM DBG connecting to websocket module=oracle provider=mexc
3:15AM DBG connecting to websocket module=oracle provider=bitget
3:15AM ERR error="error connecting to bitget websocket: x509: certificate signed by unknown authority" module=oracle provider=bitget
3:15AM DBG connecting to websocket module=oracle provider=bitget
3:15AM ERR error="error connecting to coinbase websocket: x509: certificate signed by unknown authority" module=oracle provider=coinbase
3:15AM DBG connecting to websocket module=oracle provider=coinbase
3:15AM ERR error="error connecting to okx …
```
> fix: add ca-certificates in final image
